services:
  redis:
    image: redis:latest
    container_name: the-boost-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - app-network

networks:
  app-network:
    driver: bridge