name: Build and Test

on:
  workflow_dispatch: # Déclenchement manuel
  push: # Déclenchement automatique sur push
    branches: 

     - 'test_ci-*'   # Uniquement sur les branches commençant par 'test_ci-'
    paths-ignore:    # Ignore les changements dans ces fichiers
     - '**.md'
     - 'docs/**'
     - '.gitignore'
     - 'LICENSE'

jobs:
  all-tasks:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest
    
    steps:
    # Setup environment
    - name: Checkout code
      uses: actions/checkout@v4
      # Setup nodejs
    - name: Setup Node.js  
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    # démarrage mongoDB
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '7.0'
    #Installation des dépendances
    - name: Install dependencies
      run: npm ci

    # Linting c'est la Phase de Qualité du Code
    - name: Run ESLint
      run: npm run lint
      
    # Testing
    - name: Run unit tests
      run: npm run test
      
    - name: Run e2e tests
      run: npm run test:e2e

    - name: Generate test coverage
      run: npm run test:cov
    #Sauvegarde des Rapports de couverture
    - name: Upload coverage reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ github.sha }}
        path: coverage/
        retention-days: 7
      
    # Building
    - name: Build application
      run: npm run build
    #Sauvegarde des Artifacts de Build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ github.sha }}
        path: dist/
        retention-days: 1

    # Status notification
    - name: Check status
      if: always()
      run: |
        if [[ "${{ job.status }}" == "success" ]]; then
          echo " All steps completed successfully!"
        else
          echo " One or more steps failed!"
          exit 1
        fi